<a href="https://colab.research.google.com/github/hrtywhy/Machine-Learning/blob/main/datachallenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score

In [7]:
from google.colab import drive
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
cp /content/drive/MyDrive/jaga/Desa/Penyerapan_Dana_Desa_2018.xlsx /content/

In [9]:
cp /content/drive/MyDrive/jaga/Desa/Penyerapan_Dana_Desa_2019.xlsx /content/

In [10]:
cp /content/drive/MyDrive/jaga/Desa/Penyerapan_Dana_Desa_2020.xlsx /content/

In [11]:
cp /content/drive/MyDrive/jaga/Desa/Penyerapan_Dana_Desa_2021.xlsx /content/

In [12]:
cp /content/drive/MyDrive/jaga/Desa/Desa.xlsx.xlsx /content/

In [13]:
sheet = 'Sheet1'
data_2018 = pd.read_excel("Penyerapan_Dana_Desa_2018.xlsx", sheet_name=sheet)
data_2018.head(10)

    kode_desa  tahun  ... realisasi_tahap_3 persentase_realisasi_tahap_3
0  5105022008   2018  ...           2414000                          100
1  5105022008   2018  ...          57619000                          100
2  5105022008   2018  ...          21686000                          100
3  5105022008   2018  ...                 0                            0
4  5105022008   2018  ...          34027125                          100
5  5105022008   2018  ...         120000000                          100
6  5105022008   2018  ...          33877850                          100
7  5105022008   2018  ...                 0                            0
8  5105022008   2018  ...                 0                            0
9  5105022008   2018  ...          11018000                          100

[10 rows x 14 columns]

In [14]:
sheet = 'Sheet1'
data_2019 = pd.read_excel("Penyerapan_Dana_Desa_2019.xlsx", sheet_name=sheet)
data_2019.head(10)

    kode_desa  tahun  ... realisasi_tahap_3 persentase_realisasi_tahap_3
0  5105022008   2019  ...                 0                            0
1  5105022008   2019  ...                 0                            0
2  5105022008   2019  ...                 0                            0
3  5105022008   2019  ...                 0                            0
4  5105022008   2019  ...                 0                            0
5  5105022008   2019  ...                 0                            0
6  5105022008   2019  ...                 0                            0
7  5105022008   2019  ...                 0                            0
8  5105022008   2019  ...                 0                            0
9  5105022008   2019  ...                 0                            0

[10 rows x 14 columns]

In [15]:
sheet = 'Sheet1'
data_2020 = pd.read_excel("Penyerapan_Dana_Desa_2020.xlsx", sheet_name=sheet)
data_2020.head(10)

    kode_desa  tahun  ... realisasi_tahap_3 persentase_realisasi_tahap_3
0  5105022008   2020  ...         110027000                          100
1  5105022008   2020  ...          23483800                          100
2  5105022008   2020  ...          56807000                          100
3  5105022008   2020  ...           2727500                          100
4  5105022008   2020  ...         230400000                          100
5  5105022008   2020  ...           5708000                          100
6  5105022008   2020  ...          28970100                          100
7  5105022008   2020  ...          12628000                          100
8  5105022008   2020  ...         108039800                          100
9  5105022008   2020  ...                 0                            0

[10 rows x 14 columns]

In [16]:
sheet = 'Sheet1'
data_2021 = pd.read_excel("Penyerapan_Dana_Desa_2021.xlsx", sheet_name=sheet)
data_2021.head(10)

    kode_desa  tahun  ... realisasi_tahap_3 persentase_realisasi_tahap_3
0  5105022008   2021  ...                 0                            0
1  5105022008   2021  ...                 0                            0
2  5105022008   2021  ...                 0                            0
3  5105022008   2021  ...                 0                            0
4  5105022008   2021  ...                 0                            0
5  5105022008   2021  ...                 0                            0
6  5105022008   2021  ...                 0                            0
7  5105022008   2021  ...                 0                            0
8  5105022008   2021  ...                 0                            0
9  5105022008   2021  ...                 0                            0

[10 rows x 14 columns]

In [17]:
sheet = 'Sheet1'
data_desa = pd.read_excel("Desa.xlsx.xlsx", sheet_name=sheet)
data_desa.head(10)

       nama_provinsi       nama_pemda   nama_desa  ... tahun        pagu  penyaluran
0               Bali   Kab. Klungkung         Aan  ...  2018   716994000   716994000
1               Bali   Kab. Klungkung         Aan  ...  2019   825089000  1155124600
2               Bali   Kab. Klungkung         Aan  ...  2020   824070000   618052500
3               Bali   Kab. Klungkung         Aan  ...  2021   846116000   615716000
4               Bali  Kab. Karangasem       Ababi  ...  2018   836882000   836882000
5               Bali  Kab. Karangasem       Ababi  ...  2019  1109972000  1109972000
6               Bali  Kab. Karangasem       Ababi  ...  2020  1159842000  1159842000
7               Bali  Kab. Karangasem       Ababi  ...  2021  1269368000   276147200
8  Sulawesi Tenggara  Kab. Muna Barat  Abadi Jaya  ...  2018   727098800   727098800
9  Sulawesi Tenggara  Kab. Muna Barat  Abadi Jaya  ...  2019   835397000   835397000

[10 rows x 9 columns]

In [3]:
data_2018_1 = pd.DataFrame(data_2018['realisasi_tahap_1'], data_2018['realisasi_tahap_2'], data_2018['realisasi_tahap_3'])
data_2018_1

NameError: ignored